### ISSUE TITLE
Magic instructions don't match selected trick

### ISSUE THREAD

**Issue by riggles1** [Dimedime-d/kptranslation#11]
GBA Hardware, EZFODE cartridge, clean boot.
v1.1.0 of the patch
Center Point unlocked normally, Book Test, Time Paradox, Microwave and Doctor Kururin unlocked through password codes.

Selecting these give the wrong instructions:

Book Test learn = Kururin Shock instead
Time Paradox learn = Ten and Hundred instead
Center Point learn = Book Test instead
Doctor Kururin learn = Time Paradox instead
Microwave learn = Sound Catch instead

**Comment by Dimedime-d** [comment]
Used the wrong address for finding the selected magic option. This difference isn't seen if all 16 magic tricks were already unlocked.
